---
name: Build

# Controls when the workflow will run
'on':
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  runner:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

#      - name: Set up Python 3.
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.x'

      - name: Configure Ansible
        run: |
          mkdir -p ~/.ansible
          cp .github/ansible.cfg ~/.ansible.cfg
          cp .github/hosts ~/.ansible/hosts

      - name: Show Python 3 version
        run: python3 --version

      - name: Show Pip 3 version
        run: pip3 --version

      - name: Install ansible-lint
        run: >-
          python3 -m pip install --user ansible-lint "urllib3<2"
          molecule
          molecule-plugins[docker]
          # run: python3 -m pip install --upgrade --user ansible-lint

      - name: Show Ansible version
        run: ansible --version

      - name: Show system setup
        run: ansible localhost -m setup

      - name: Show Molecule version
        run: molecule --version

      - name: Show ansible-lint version
        run: ansible-lint --version

      - name: Show YamlLint version
        run: yamllint --version

      - name: Show Docker version
        run: docker --version

      - name: Show Docker Compose version
        run: docker-compose --version

      - name: Check buildah and podman version
        run: |
          echo "podman version"
          podman version
          echo "buildah version"
          buildah version

      - name: Show buildah and podman info
        run: |
          echo "podman info"
          podman info
          echo
          echo "buildah info"
          buildah info

# vim:set nu expandtab ts=2 sw=2 sts=2:
