---
name: Build

# Controls when the workflow will run
'on':
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "47 3 * * 0"

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

#      - name: Set up Python 3.
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.x'

      - name: Show Ansible version
        run: ansible --version

      - name: Check buildah and podman version
        run: |
          echo "podman version"
          podman version
          echo "buildah version"
          buildah version

# vim:set nu expandtab ts=2 sw=2 sts=2:
